export const ENDPOINT = 'https://geektrust.s3.ap-southeast-1.amazonaws.com/coding-problems/shopping-cart/catalogue.json';
export const COLOURS_LIST = ["Red", "Blue", "Green"];
export const GENDER_LIST = ["Men", "Women"];
export const PRICE_LIST = ["0 - 250", "250 - 450", "450 - 100000"];
export const CLOTH_TYPE_LIST = ["Polo", "Hoodie", "Basic"];
export const TRY_AGAIN = "Oops something went wrong, please try again.";
export const DUPLICATE = "You've already added this item to your cart. Go to your cart to review or update your selection";
export const MAX_QUANTITY = "You've reached maximum quantity available";
export const ORDER_PLACED = "Order placed successfully!";